server:
  port: 8080

spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true

  logging:
    level:
      com.tutorial: debug

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

cloud:
  aws:
    credentials:
      accessKey: AKIASBZTU4IV22KYHZXY
      secretKey: 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
    s3:
      bucket: acutecritic
    region:
      static: ap-northeast-2
    stack:
      auto: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB